#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"AlwaysOnDM", {PERSISTENT | BACKUP, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT | BACKUP, BOOL}},
    {"DisableUpdates", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DisengageOnAccelerator", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY | BACKUP, BOOL}},
    {"ExperimentalMode", {PERSISTENT | BACKUP, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT | BACKUP, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT | BACKUP, STRING}},
    {"GithubUsername", {PERSISTENT | BACKUP, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT | BACKUP, STRING}},
    {"GsmMetered", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT | BACKUP, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"IsMetric", {PERSISTENT | BACKUP, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT | BACKUP, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT | BACKUP, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT | BACKUP, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT | BACKUP, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT | BACKUP, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RecordFront", {PERSISTENT | BACKUP, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG | BACKUP, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT | BACKUP, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TorqueBar", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UsbGpuPresent", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"UsbGpuCompiled", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"Version", {PERSISTENT, STRING}},

    // --- sunnypilot params --- //
    {"ApiCache_DriveStats", {PERSISTENT, JSON}},
    {"AutoLaneChangeBsmDelay", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"AutoLaneChangeTimer", {PERSISTENT | BACKUP, INT, "0"}},
    {"BlinkerLateralReengageDelay", {PERSISTENT | BACKUP, INT, "0"}},  // seconds
    {"BlinkerMinLateralControlSpeed", {PERSISTENT | BACKUP, INT, "20"}},  // MPH or km/h
    {"BlinkerPauseLateralControl", {PERSISTENT | BACKUP, INT, "0"}},
    {"Brightness", {PERSISTENT | BACKUP, INT, "0"}},
    {"CarList", {PERSISTENT, JSON}},
    {"CarParamsSP", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsSPCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsSPPersistent", {PERSISTENT, BYTES}},
    {"CarPlatformBundle", {PERSISTENT | BACKUP, JSON}},
    {"ChevronInfo", {PERSISTENT | BACKUP, INT, "4"}},
    {"CompletedSunnylinkConsentVersion", {PERSISTENT, STRING, "0"}},
    {"CustomAccIncrementsEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"CustomAccLongPressIncrement", {PERSISTENT | BACKUP, INT, "5"}},
    {"CustomAccShortPressIncrement", {PERSISTENT | BACKUP, INT, "1"}},
    {"DeviceBootMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"DevUIInfo", {PERSISTENT | BACKUP, INT, "0"}},
    {"EnableCopyparty", {PERSISTENT | BACKUP, BOOL}},
    {"EnableGithubRunner", {PERSISTENT | BACKUP, BOOL}},
    {"GreenLightAlert", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"GithubRunnerSufficientVoltage", {CLEAR_ON_MANAGER_START , BOOL}},
    {"HasAcceptedTermsSP", {PERSISTENT, STRING, "0"}},
    {"HideVEgoUI", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"IntelligentCruiseButtonManagement", {PERSISTENT | BACKUP , BOOL}},
    {"InteractivityTimeout", {PERSISTENT | BACKUP, INT, "0"}},
    {"IsDevelopmentBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsReleaseSpBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"LastGPSPositionLLK", {PERSISTENT, STRING}},
    {"LeadDepartAlert", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"MaxTimeOffroad", {PERSISTENT | BACKUP, INT, "1800"}},
    {"ModelRunnerTypeCache", {CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"OffroadMode", {CLEAR_ON_MANAGER_START, BOOL}},
    {"Offroad_TiciSupport", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadScreenOffBrightness", {PERSISTENT | BACKUP, INT, "0"}},
    {"OnroadScreenOffBrightnessMigrated", {PERSISTENT | BACKUP, STRING, "0.0"}},
    {"OnroadScreenOffTimer", {PERSISTENT | BACKUP, INT, "15"}},
    {"OnroadScreenOffTimerMigrated", {PERSISTENT | BACKUP, STRING, "0.0"}},
    {"OnroadUploads", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"QuickBootToggle", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"QuietMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RainbowMode", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"RocketFuel", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ShowAdvancedControls", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ShowTurnSignals", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"StandstillTimer", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TrueVEgoUI", {PERSISTENT | BACKUP, BOOL, "0"}},

    // MADS params
    {"Mads", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsMainCruiseAllowed", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"MadsSteeringMode", {PERSISTENT | BACKUP, INT, "0"}},
    {"MadsUnifiedEngagementMode", {PERSISTENT | BACKUP, BOOL, "1"}},

    // Model Manager params
    {"ModelManager_ActiveBundle", {PERSISTENT, JSON}},
    {"ModelManager_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ModelManager_DownloadIndex", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"ModelManager_Favs", {PERSISTENT | BACKUP, STRING}},
    {"ModelManager_LastSyncTime", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_ModelsCache", {PERSISTENT | BACKUP, JSON}},

    // Neural Network Lateral Control
    {"NeuralNetworkLateralControl", {PERSISTENT | BACKUP, BOOL, "0"}},

    // sunnylink params
    {"EnableSunnylinkUploader", {PERSISTENT | BACKUP, BOOL}},
    {"LastSunnylinkPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"ParamsVersion", {PERSISTENT, INT}},
    {"SunnylinkCache_Roles", {PERSISTENT, STRING}},
    {"SunnylinkCache_Users", {PERSISTENT, STRING}},
    {"SunnylinkDongleId", {PERSISTENT, STRING}},
    {"SunnylinkdPid", {PERSISTENT, INT}},
    {"SunnylinkEnabled", {PERSISTENT, BOOL, "1"}},
    {"SunnylinkTempFault", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL, "0"}},

    // Backup Manager params
    {"BackupManager_CreateBackup", {PERSISTENT, BOOL}},
    {"BackupManager_RestoreVersion", {PERSISTENT, STRING}},

    // sunnypilot car specific params
    {"HyundaiLongitudinalTuning", {PERSISTENT | BACKUP, INT, "0"}},
    {"SubaruStopAndGo", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"SubaruStopAndGoManualParkingBrake", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TeslaCoopSteering", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ToyotaEnforceStockLongitudinal", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"ToyotaStopAndGoHack", {PERSISTENT | BACKUP, BOOL, "0"}},

    {"DynamicExperimentalControl", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"BlindSpot", {PERSISTENT | BACKUP, BOOL, "0"}},

    // sunnypilot model params
    {"CameraOffset", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"LagdToggle", {PERSISTENT | BACKUP, BOOL, "1"}},
    {"LagdToggleDelay", {PERSISTENT | BACKUP, FLOAT, "0.2"}},
    {"LagdValueCache", {PERSISTENT, FLOAT, "0.2"}},
    {"LaneTurnDesire", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"LaneTurnValue", {PERSISTENT | BACKUP, FLOAT, "19.0"}},
    {"PlanplusControl", {PERSISTENT | BACKUP, FLOAT, "1.0"}},

    // mapd
    {"MapAdvisorySpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT}},
    {"MapdVersion", {PERSISTENT, STRING}},
    {"MapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0.0"}},
    {"NextMapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_OSMUpdateRequired", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmDbUpdatesCheck", {CLEAR_ON_MANAGER_START, BOOL}},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", {PERSISTENT, STRING}},
    {"OsmDownloadedDate", {PERSISTENT, STRING, "0.0"}},
    {"OSMDownloadLocations", {PERSISTENT, JSON}},
    {"OSMDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmLocal", {PERSISTENT, BOOL}},
    {"OsmLocationName", {PERSISTENT, STRING}},
    {"OsmLocationTitle", {PERSISTENT, STRING}},
    {"OsmLocationUrl", {PERSISTENT, STRING}},
    {"OsmStateName", {PERSISTENT, STRING, "All"}},
    {"OsmStateTitle", {PERSISTENT, STRING}},
    {"OsmWayTest", {PERSISTENT, STRING}},
    {"RoadName", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"RoadNameToggle", {PERSISTENT | BACKUP, BOOL, "0"}},

    // Speed Limit
    {"SpeedLimitMode", {PERSISTENT | BACKUP, INT, "1"}},
    {"SpeedLimitOffsetType", {PERSISTENT | BACKUP, INT, "0"}},
    {"SpeedLimitPolicy", {PERSISTENT | BACKUP, INT, "3"}},
    {"SpeedLimitValueOffset", {PERSISTENT | BACKUP, INT, "0"}},

    // Smart Cruise Control
    {"MapTargetVelocities", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"SmartCruiseControlMap", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"SmartCruiseControlVision", {PERSISTENT | BACKUP, BOOL, "0"}},

    // Torque lateral control custom params
    {"CustomTorqueParams", {PERSISTENT | BACKUP , BOOL}},
    {"EnforceTorqueControl", {PERSISTENT | BACKUP, BOOL}},
    {"LiveTorqueParamsToggle", {PERSISTENT | BACKUP , BOOL}},
    {"LiveTorqueParamsRelaxedToggle", {PERSISTENT | BACKUP , BOOL}},
    {"TorqueControlTune", {PERSISTENT | BACKUP, FLOAT, "0.0"}},
    {"TorqueParamsOverrideEnabled", {PERSISTENT | BACKUP, BOOL, "0"}},
    {"TorqueParamsOverrideFriction", {PERSISTENT | BACKUP, FLOAT, "0.1"}},
    {"TorqueParamsOverrideLatAccelFactor", {PERSISTENT | BACKUP, FLOAT, "2.5"}},

    // CarrotPilot integration keys
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"LongitudinalPersonalityMax", {PERSISTENT, INT, "3"}},
    {"NetworkAddress", {CLEAR_ON_MANAGER_START, STRING}},
    {"ScreenRecord", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL} },
    {"CarrotNaviDebug", {CLEAR_ON_MANAGER_START, STRING} },
    {"CarrotNaviImage", {CLEAR_ON_MANAGER_START, STRING} },
    {"CarrotNaviWebBootstrapRequest", {CLEAR_ON_MANAGER_START, STRING} },
    {"CarrotVisionActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL} },
    {"TrafficLight", {CLEAR_ON_MANAGER_START, STRING} },
    {"ApiCache_NavDestinations", {PERSISTENT, STRING}},
    {"NavDestination", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"NavDestinationWaypoints", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"NavPastDestinations", {PERSISTENT, STRING}},
    {"NavSettingLeftSide", {PERSISTENT, BOOL}},
    {"NavSettingTime24h", {PERSISTENT, BOOL}},
    {"MapboxStyle", {PERSISTENT, INT}},
    {"MapboxPublicKey", {PERSISTENT, STRING}},
    {"MapboxSecretKey", {PERSISTENT, STRING}},
    {"GMapKey", {PERSISTENT, STRING}},
    {"SearchInput", {PERSISTENT, INT}},
    {"CarSelected3", {PERSISTENT, STRING, "MOCK"}},
    {"SupportedCars", {PERSISTENT, STRING}},
    {"SupportedCars_gm", {PERSISTENT, STRING}},
    {"SupportedCars_toyota", {PERSISTENT, STRING}},
    {"SupportedCars_mazda", {PERSISTENT, STRING}},
    {"SupportedCars_ford", {PERSISTENT, STRING}},
    {"SupportedCars_vw", {PERSISTENT, STRING}},
    {"SupportedCars_tesla", {PERSISTENT, STRING}},
    {"ShowDebugUI", {PERSISTENT, INT, "0"}},
    {"ShowDateTime", {PERSISTENT, INT, "1"}},
    {"ShowLaneInfo", {PERSISTENT, INT, "1"}},
    {"ShowRadarInfo", {PERSISTENT, INT, "1"}},
    {"ShowDeviceState", {PERSISTENT, INT, "1"}},
    {"ShowPathMode", {PERSISTENT, INT, "9"}},
    {"ShowPathColor", {PERSISTENT, INT, "13"}},
    {"ShowPathColorCruiseOff", {PERSISTENT, INT, "19"}},
    {"ShowPathModeLane", {PERSISTENT, INT, "14"}},
    {"ShowPathColorLane", {PERSISTENT, INT, "13"}},
    {"ShowPlotMode", {PERSISTENT, INT, "0"}},
    {"TimezoneName", {PERSISTENT, STRING, ""}},                // 로컬 타임존 IANA 이름 (예: "Asia/Seoul"), 앱/WiFi/GPS로 해석되면 기록
    {"TimezoneSource", {PERSISTENT, STRING, ""}},              // 타임존 출처 우선순위 추적 ("app" > "wifi" > "gps")
    {"CarrotTireTrajectory", {PERSISTENT, INT, "0"}},
    {"ShowCustomBrightness", {PERSISTENT, INT, "100"}},
    {"ShowModelView", {PERSISTENT, INT, "0"}},
    {"ClusterHud", {PERSISTENT, INT, "0"}},
    {"ClusterHudConnected", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ClusterHudDebug", {PERSISTENT, INT, "0"}},
    {"ClusterHudBrightness", {PERSISTENT, INT, "0"}},
    {"ClusterHudMirror", {PERSISTENT, INT, "0"}},
    {"ClusterHudEncoder", {PERSISTENT, INT, "0"}},
    {"ClusterHudCoreMode", {PERSISTENT, INT, "0"}},
    {"ClusterHudPriority", {PERSISTENT, INT, "10"}},
    {"ClusterHudTheme", {PERSISTENT, INT, "0"}},
    {"ClusterNaviMapTheme", {PERSISTENT, INT, "1"}},
    {"ClusterNaviMapType", {PERSISTENT, INT, "0"}},
    {"ClusterNaviMapFps", {PERSISTENT, INT, "1"}},
    {"ClusterHudLiveFps", {PERSISTENT, INT, "1"}},
    {"ClusterHudScreenMode", {PERSISTENT, INT, "0"}},
    {"ClusterHudCameraViewMode", {PERSISTENT, INT, "0"}},
    {"ClusterHudRadarInfo", {PERSISTENT, INT, "4"}},
    {"ClusterHudRadarDisplay", {PERSISTENT, INT, "0"}},
    {"ClusterHudRadarSourceColor", {PERSISTENT, INT, "0"}},
    {"RecordRoadCam", {PERSISTENT, INT, "0"}},
    {"CarrotYouTubeLive", {PERSISTENT, INT, "0"}},
    {"CarrotYouTubeQuality", {PERSISTENT, INT, "0"}},
    {"CarrotYouTubeTimestamp", {PERSISTENT, INT, "0"}},
    {"HDPuse", {PERSISTENT, INT, "0"}},
    {"AutoCruiseControl", {PERSISTENT, INT, "0"}},
    {"CruiseEcoControl", {PERSISTENT, INT, "2"}},
    {"CarrotCruiseDecel", {PERSISTENT, INT, "-1"}},
    {"CarrotCruiseAtcDecel", {PERSISTENT, INT, "-1"}},
    {"AutoGasTokSpeed", {PERSISTENT, INT, "0"}},
    {"AutoGasCancelSpeed", {PERSISTENT, INT, "30"}},
    {"AutoGasSyncSpeed", {PERSISTENT, INT, "1"} },
    {"ApplyModelSpeed", {PERSISTENT, INT, "0"} },
    {"AutoEngage", {PERSISTENT, INT, "0"}},
    {"AlwaysLateral", {PERSISTENT, INT, "1"} },
    {"DisableMinSteerSpeed", {PERSISTENT, INT, "0"}},
    {"AutoCurveSpeedLowerLimit", {PERSISTENT, INT, "30"}},
    {"AutoCurveSpeedFactor", {PERSISTENT, INT, "120"}},
    {"AutoTurnControl", {PERSISTENT, INT, "0"}},
    {"AutoTurnControlSpeedTurn", {PERSISTENT, INT, "20"}},
    {"AutoTurnControlTurnEnd", {PERSISTENT, INT, "6"}},
    {"AutoTurnMapChange", {PERSISTENT, INT, "0"}},
    {"AutoNaviSpeedCtrlEnd", {PERSISTENT, INT, "7"}},
    {"AutoNaviSpeedCtrlMode", {PERSISTENT, INT, "2"}},
    {"AutoRoadSpeedLimitOffset", {PERSISTENT, INT, "-1"}},
    {"AutoNaviSpeedBumpTime", {PERSISTENT, INT, "1"}},
    {"AutoNaviSpeedBumpSpeed", {PERSISTENT, INT, "35"}},
    {"AutoNaviSpeedDecelRate", {PERSISTENT, INT, "120"}},
    {"AutoNaviSpeedSafetyFactor", {PERSISTENT, INT, "105"}},
    {"AutoNaviCountDownMode", {PERSISTENT, INT, "2"}},
    {"TurnSpeedControlMode", {PERSISTENT, INT, "1"}},
    {"MapTurnSpeedFactor", {PERSISTENT, INT, "90"}},
    {"ModelTurnSpeedFactor", {PERSISTENT, INT, "0"}},
    {"StoppingAccel", {PERSISTENT, INT, "-50"}},
    {"AutoSpeedUptoRoadSpeedLimit", {PERSISTENT, INT, "0"}},
    {"AutoRoadSpeedAdjust", {PERSISTENT, INT, "50"}},
    {"StopDistanceCarrot", {PERSISTENT, INT, "550"}},
    {"JLeadFactor3", {PERSISTENT, INT, "0"}},
    {"CruiseButtonMode", {PERSISTENT, INT, "0"}},
    {"CancelButtonMode", {PERSISTENT, INT, "0"}},
    {"LfaButtonMode", {PERSISTENT, INT, "0"}},
    {"CruiseButtonTest1", {PERSISTENT, INT, "8"}},
    {"CruiseButtonTest2", {PERSISTENT, INT, "30"}},
    {"CruiseButtonTest3", {PERSISTENT, INT, "1"}},
    {"CruiseSpeedUnit", {PERSISTENT, INT, "10"}},
    {"CruiseButtonLongDelay", {PERSISTENT, INT, "40"} },
    {"CruiseSpeedUnitBasic", {PERSISTENT, INT, "1"}},
    {"CruiseSpeed1", {PERSISTENT, INT, "30"}},
    {"CruiseSpeed2", {PERSISTENT, INT, "50"}},
    {"CruiseSpeed3", {PERSISTENT, INT, "80"}},
    {"CruiseSpeed4", {PERSISTENT, INT, "110"}},
    {"CruiseSpeed5", {PERSISTENT, INT, "130"}},
    {"PaddleMode", {PERSISTENT, INT, "0"}},
    {"MyDrivingMode", {PERSISTENT, INT, "3"}},
    {"MyDrivingModeAuto", {PERSISTENT, INT, "0"}},
    {"TrafficLightDetectMode", {PERSISTENT, INT, "2"}},
    {"SteerActuatorDelay", {PERSISTENT, INT, "0"}},
    {"LatSmoothSec", {PERSISTENT, INT, "13"}},
    {"LatSuspendAngleDeg", {PERSISTENT, INT, "300"}},
    {"CruiseOnDist", {PERSISTENT, INT, "400"}},
    {"CruiseMaxVals0", {PERSISTENT, INT, "160"}},
    {"CruiseMaxVals1", {PERSISTENT, INT, "200"}},
    {"CruiseMaxVals2", {PERSISTENT, INT, "160"}},
    {"CruiseMaxVals3", {PERSISTENT, INT, "130"}},
    {"CruiseMaxVals4", {PERSISTENT, INT, "110"}},
    {"CruiseMaxVals5", {PERSISTENT, INT, "95"}},
    {"CruiseMaxVals6", {PERSISTENT, INT, "80"}},
    {"LongTuningKpV", {PERSISTENT, INT, "100"}},
    {"LongTuningKiV", {PERSISTENT, INT, "0"}},
    {"LongTuningKf", {PERSISTENT, INT, "100"}},
    {"LongActuatorDelay", {PERSISTENT, INT, "20"}},
    {"VEgoStopping", {PERSISTENT, INT, "50"}},
    {"RadarReactionFactor", {PERSISTENT, INT, "100"}},
    {"EnableRadarTracks", {PERSISTENT, INT, "0"}},
    {"RadarLatFactor", {PERSISTENT, INT, "0"}},
    {"EnableCornerRadar", {PERSISTENT, INT, "0"}},
    {"RadarLeadModelMode", {PERSISTENT, INT, "0"}},
    {"EnableRadarTracksResult", {PERSISTENT | CLEAR_ON_MANAGER_START, INT}},
    {"CanParserResult", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"HotspotOnBoot", {PERSISTENT, INT, "0"}},
    {"SoftwareMenu", {PERSISTENT, INT, "1"}},
    {"HyundaiCameraSCC", {PERSISTENT, INT, "0"}},
    {"FingerPrints", {PERSISTENT | CLEAR_ON_MANAGER_START, STRING}},
    {"IsLdwsCar", {PERSISTENT, INT, "0"}},
    {"CanfdHDA2", {PERSISTENT, INT, "0"}},
    {"CanfdDebug", {PERSISTENT, INT, "0"}},
    {"SoundVolumeAdjust", {PERSISTENT, INT, "100"}},
    {"SoundVolumeAdjustEngage", {PERSISTENT, INT, "10"}},
    {"SoundLanguageSetting", {PERSISTENT, STRING, "auto"}},
    {"TFollowGap1", {PERSISTENT, INT, "110"}},
    {"TFollowGap2", {PERSISTENT, INT, "120"}},
    {"TFollowGap3", {PERSISTENT, INT, "140"}},
    {"TFollowGap4", {PERSISTENT, INT, "160"}},
    {"DynamicTFollow", {PERSISTENT, INT, "0"}},
    {"DynamicTFollowLC", {PERSISTENT, INT, "100"}},
    {"TFollowDecelBoost", {PERSISTENT, INT, "50"}},
    {"EnableSpeedTF", {PERSISTENT, INT, "0"}},
    {"AChangeCostStarting", {PERSISTENT, INT, "10"}},
    {"TrafficStopDistanceAdjust", {PERSISTENT, INT, "-150"}},
    {"HapticFeedbackWhenSpeedCamera", {PERSISTENT, INT, "0"}},
    {"UseLaneLineSpeed", {PERSISTENT, INT, "0"}},
    {"UseLaneLineCurveSpeed", {PERSISTENT, INT, "0"}},
    {"AdjustLaneOffset", {PERSISTENT, INT, "0"}},
    {"LaneChangeNeedTorque", {PERSISTENT, INT, "0"}},
    {"LaneChangeDelay", {PERSISTENT, INT, "0"}},
    {"LaneChangeBsd", {PERSISTENT, INT, "0"}},
    {"LaneLineCheck", {PERSISTENT, INT, "0"}},
    {"MaxAngleFrames", {PERSISTENT, INT, "89"}},
    {"SoftHoldMode", {PERSISTENT, INT, "0"}},
    {"LatMpcPathCost", {PERSISTENT, INT, "200"}},
    {"LatMpcMotionCost", {PERSISTENT, INT, "7"}},
    {"LatMpcAccelCost", {PERSISTENT, INT, "120"}},
    {"LatMpcJerkCost", {PERSISTENT, INT, "4"}},
    {"LatMpcSteeringRateCost", {PERSISTENT, INT, "7"}},
    {"LatMpcInputOffset", {PERSISTENT, INT, "4"}},
    {"PathOffset", {PERSISTENT, INT, "0"}},
    {"CameraYawTrimDeg", {PERSISTENT, INT, "0"}},
    {"LateralTorqueCustom", {PERSISTENT, INT, "0"}},
    {"LateralTorqueAccelFactor", {PERSISTENT, INT, "2500"}},
    {"LateralTorqueFriction", {PERSISTENT, INT, "100"}},
    {"LateralTorqueKpV", {PERSISTENT, INT, "100"}},
    {"LateralTorqueKiV", {PERSISTENT, INT, "10"}},
    {"LateralTorqueKf", {PERSISTENT, INT, "100"}},
    {"LateralTorqueKd", {PERSISTENT, INT, "0"}},
    {"CustomSteerMax", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUp", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaDown", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUpLC", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaDownLC", {PERSISTENT, INT, "0"}},
    {"SpeedFromPCM", {PERSISTENT, INT, "2"}},
    {"MaxTimeOffroadMin", {PERSISTENT, INT, "60"}},
    {"DisableDM", {PERSISTENT, INT, "0"}},
    {"MuteDoor", {PERSISTENT, INT, "0"}},
    {"MuteSeatbelt", {PERSISTENT, INT, "0"}},
    {"CarrotException", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarrotExceptionSent", {CLEAR_ON_MANAGER_START, BOOL}},
    {"CarrotExceptionDiscordWebhookUrl", {PERSISTENT, STRING}},
    {"CarName", {PERSISTENT, STRING}},
    {"EVTable", {PERSISTENT, BOOL, "0"}},
    {"LongPitch", {PERSISTENT, BOOL, "0"}},
    {"ActivateCruiseAfterBrake", {CLEAR_ON_MANAGER_START, INT, "0"}},
    {"CustomSR", {PERSISTENT, INT, "0"}},
    {"SteerRatioRate", {PERSISTENT, INT, "100"}},
    {"SoftRestartTriggered", {CLEAR_ON_MANAGER_START, INT}},
    {"DevicePosition", {CLEAR_ON_MANAGER_START, STRING}},
    {"NNFF", {PERSISTENT, INT, "0"}},
    {"NNFFLite", {PERSISTENT, INT, "0"}},
    {"NNFFModelName", {CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"HardwareC3xLite", {PERSISTENT, INT, "0"}},
    {"ShareData", {PERSISTENT, INT, "0"}},
};
